### PR TITLE
Register fix

### LINKED ISSUE #66: broken signup: "415 Unsupported Media Type"
the same issue we had with login; remove `mode:'no-cors'` header and set `Access-Control-Allow-Origin: '*'`

### PR DESCRIPTION
**Pull request by vhong000**
close #66 #67 

fixed fetch header and refactored registration form into `redux-form` and using dropdown for selecting school.

### CODE REVIEW

File: frontend/src/components/register/register.js [hunk 1]
```diff
@@ -1,181 +1,221 @@
...
+
+Register.defaultProps = {
+	applicant: {},
+	schools: [],
+}
 
-export default connect(mapStateToProps,{ registerUser })(Register);
+export default reduxForm({
+	form: 'registerForm',
+	validate,
```
Comment (drsh0x) [inline frontend/src/components/register/register.js]: is there a reason you're doing async validation in `Register`? it seems that change/blur events set `asyncValidating` so redux-form expects a promise and your `validate` is synchronous. This causes the form to become laggy/unresponsive. If you're not fetching data, try this :

```suggestion
	validate,
	asyncBlurFields: [],
```

peek 2018-10-29 18-25

Comment (vhong000) [reply frontend/src/components/register/register.js]: ahh I was trying to figure this out. Guess I missed that part of the docs :/
